micronaut:
  application:
    name: micronaut-bugreport-bigdecimal

jackson:
  serialization-inclusion: "USE-DEFAULTS"
  generator:
    WRITE_BIGDECIMAL_AS_PLAIN: true
  deserialization:
    USE_BIG_DECIMAL_FOR_FLOATS: true
